import numpy as np

from typing import List

def print_galton_board(data: List[int]) -> None:
    """
    prints a basic galton board based on data generated
    by the galton() function.

    Parameters
    ----------
    data : List[int,...]
        list with sum of balls falling within each of the "num_bins" bins.
        Generated by the galton() function.

    Returns
    -------
    None.

    """
    for val in data:
        # print for each bin a dot for each ball
        for i in np.arange(0, val):
            
            print(".", end="")
        # show total number of balls within each bin at the end of the line
        print(val)
